steps:
  # Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--build-arg', '-t', 'gcr.io/intake-project-try1/cogetix-frontend:latest', '.']

  # Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/intake-project-try1/cogetix-frontend:latest']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args: ['gcloud', 'functions', 'deploy', '--trigger-http', '--runtime=nodejs20', '--region=europe-west1', '--source=.']

images:
  - 'gcr.io/intake-project-try1/cogetix-frontend:latest'
